creating 1D, 2D, and 3D arrays

In [2]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(type(a))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [4]:
a=np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(a)
print(type(a))

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
<class 'numpy.ndarray'>


checking array dimensions and data types

In [5]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a.shape)
print(a.ndim)
print(a.dtype)

(2, 4)
2
int64


 indexing and slicing

In [7]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a[1,1])#indexing
print(a[1,1:])#slicing

6
[6 7 8]


reshaping array

In [8]:
a=np.array([1,2,3,4,5,6,7,8])
print(a.reshape(2,4))

[[1 2 3 4]
 [5 6 7 8]]


generating arrays using functions such as zeros(), ones(), arange(), and linspace()

In [10]:
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
a=np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
a=np.arange(1,10,3)
print(a)

[1 4 7]


In [16]:
a=np.linspace(0,12,4)
print(a)

[ 0.  4.  8. 12.]


vectorized operations

In [18]:
a=np.array([1,2,3,4,5])
print(a+2)
print(a*2)
print(a**2)

[3 4 5 6 7]
[ 2  4  6  8 10]
[ 1  4  9 16 25]


boolean masking

In [22]:
a=np.array([2,5,6,11,23,34])
print((a>5)&(a<30))
print(a[a>5])

[False False  True  True  True False]
[ 6 11 23 34]


 broadcasting

In [23]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([5,10,15])
print(a+b)

[[ 6 12 18]
 [ 9 15 21]]


aggregate functions such as sum(), mean(), min(), max() and median()

In [29]:
a=np.array([1,2,3,4,5,6])
print(a.sum())
print(a.mean())
print(a.min())
print(a.max())
print(np.median(a))

21
3.5
1
6
3.5
